version: 2.1
executors:
  terraform: # declares a reusable executor
    docker:
      - image: hashicorp/terraform:0.11.13
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: application_default_credentials.json

  # Improvement This can break down in different steps
jobs:
  build:
    executor: terraform
    steps:
      - checkout
      - run: echo $DEFAULT_APPLICATION_CREDENTIALS_FILE | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - run: terraform init -backend-config=bucket=tw-in-a-box-projects-terraform-state -backend-config=prefix=staging
      - run: terraform plan -var-file staging.tfvars -out=terraform.stg.plan
      # We could make this step manual.
      - run: terraform apply "terraform.stg.plan"
