version: 2.1
executors:
  terraform: # declares a reusable executor
    docker:
      - image: hashicorp/terraform:0.11.13
    
jobs:
  build:
    executor: terraform
    steps:
      - checkout
      - run: terraform -version
